name: 'Laravel Forge Deploy Action'
description: 'Trigger Laravel Forge Deployments with Github Actions'
author: 'ItsNash0'
branding:
  icon: upload-cloud
  color: green
inputs:
  trigger_url:
    description: 'The Deployment Trigger URL'
    required: true
  site_label:
    description: 'A label for the site'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TRIGGER_URL: ${{ inputs.trigger_url }}
    SITE_LABEL: ${{ inputs.site_label }}

