name: 'Laravel Forge Deploy Action'
description: 'Trigger Laravel Forge Deployments with Github actions'
author: 'jbrooksuk'
branding:
  icon: upload-cloud
  color: green
inputs:
  webhook_url:
    description: 'The Deployment Trigger URL'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    WEBHOOK_URL: ${{ inputs.webhook_url }}
